services:
  frontend:
    build:
      context: ./Front-End
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://backend:5001/api
    depends_on:
      - backend
  backend:
    build:
      context: ./Back-End
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=mysql://root:1234@mysql:3306/beautybook
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: beautybook
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
